### ISSUE TITLE
implement CHANGELOG.md file in the root of this repo

### ISSUE THREAD

**Issue by ofrei** [unioslo/tsd-api-client#131]
I've totally missed when ``--basic`` authentication feature was implemented for TACL, and thus keep using tsd-s3cmd's ``--get-token-for-put``. Things like CHANGELOG would really help users to identify  when such new features became available. I found https://keepachangelog.com/en/1.1.0/ to be quite helpful trying to follow this in my own repos.

Same request applies to https://github.com/unioslo/tsd-s3cmd repo ; should I submit it as a separate ticket?

**Comment by haatveit** [comment]
We already provide a changelog via the [release notes](https://github.com/unioslo/tsd-api-client/releases) here on GitHub since last year, but I'm not against adding a file to the repo if its maintenance can be automated. Perhaps worth looking into [available](https://github.com/marketplace/actions/keep-a-changelog-action) [actions](https://github.com/marketplace/actions/keep-a-changelog-new-release) for this functionality.
